// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfgDsgwG8tyec4Blg6jlYsw7uQZ97IOqM',
    appId: '1:193135757173:web:5efd992616b9738a94b53c',
    messagingSenderId: '193135757173',
    projectId: 'campusmart-12d1f',
    authDomain: 'campusmart-12d1f.firebaseapp.com',
    storageBucket: 'campusmart-12d1f.firebasestorage.app',
    measurementId: 'G-KC2EPQKG2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEOS0yQ1Gi9yutqMxHZZVwHXT2vE8mPG0',
    appId: '1:193135757173:android:f7c96ef279a67f6994b53c',
    messagingSenderId: '193135757173',
    projectId: 'campusmart-12d1f',
    storageBucket: 'campusmart-12d1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUtJO-o6YSJ0YrLFrfV3SgOQ_ooIMRmZQ',
    appId: '1:193135757173:ios:8bd9fdac7140d87194b53c',
    messagingSenderId: '193135757173',
    projectId: 'campusmart-12d1f',
    storageBucket: 'campusmart-12d1f.firebasestorage.app',
    iosBundleId: 'com.example.shopify1',
  );
}
